name: Notes CI

on:
  push:
  pull_request:
    branches: [master]

jobs:

  job:
    name: Validate Notes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Notes
        run: |
          set -x
          yq() {
          docker run --rm -i -v "${PWD}":/workdir mikefarah/yq:latest "$@"
          }
          yq e 'true' documents.yml # Validate documents.yml
          IFS=$(echo -en "\n\b") # Handle spaces correctly
          for SRC in $(yq e '.notes.*.*.path' documents.yml)
          do
            echo "Checking $SRC"
            (cd "$SRC" && docker run --rm -v "$PWD:/data" dungeonrevealer/notes-validator:latest) # Validate folder
            echo "#################################"
          done
